module:
  addtoany: 0
  allowed_formats: 0
  asset_injector: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  config_direct_save: 0
  config_update: 0
  contact: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  di_media: 0
  di_paragraphs: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  eva: 0
  features: 0
  features_ui: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  file_mdm_exif: 0
  file_mdm_font: 0
  filter: 0
  geofield: 0
  google_analytics: 0
  help: 0
  history: 0
  image: 0
  image_effects: 0
  image_widget_crop: 0
  link: 0
  linkit: 0
  maxlength: 0
  media: 0
  media_library: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  mixitup_views: 0
  name: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs_type_permissions: 0
  path: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  redirect_domain: 0
  search: 0
  shortcut: 0
  simple_block: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  tracker: 0
  update: 0
  user: 0
  views_bulk_operations: 0
  views_ui: 0
  viewsreference: 0
  webform: 0
  webform_ui: 0
  extlink: 1
  menu_link_content: 1
  pathauto: 1
  webform_bootstrap: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  bootstrap: 0
  di_stlawu: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
